# Generated by Django 4.1.3 on 2022-12-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createissue',
            name='issue_screenshort',
        ),
        migrations.AddField(
            model_name='createissue',
            name='issue_image',
            field=models.ImageField(default='default-bug.jpg', null=True, upload_to='screenshorts'),
        ),
    ]
