# Generated by Django 4.1.3 on 2022-12-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_bugticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=150),
        ),
    ]
